-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 15:38:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ventas` ;

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET utf8 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Clientes` (
  `Cientes_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `CP` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`Cientes_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Pedido` (
  `Pedido_ID` INT NOT NULL AUTO_INCREMENT,
  `Cliente_ID` INT NOT NULL,
  `N_Cliente` VARCHAR(45) NOT NULL,
  `Cal_Cliente` VARCHAR(45) NOT NULL,
  `Ciu_Cliente` VARCHAR(45) NOT NULL,
  `Est_Cliente` VARCHAR(45) NOT NULL,
  `CP_Cliente` VARCHAR(45) NOT NULL,
  `anio` VARCHAR(4) NOT NULL,
  `Producto_ID` INT NOT NULL,
  `dia` VARCHAR(45) NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pedido_ID`, `Producto_ID`),
  INDEX `idcliente_idx` (`Cliente_ID` ASC) VISIBLE,
  CONSTRAINT `idcliente`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `ventas`.`Clientes` (`Cientes_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`tipos` ;

CREATE TABLE IF NOT EXISTS `ventas`.`tipos` (
  `playeras` VARCHAR(20) NOT NULL,
  `tazas` VARCHAR(20) NULL,
  `playeras sub` VARCHAR(20) NULL,
  `playeras estam` VARCHAR(20) NULL,
  PRIMARY KEY (`playeras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Producto` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Producto` (
  `Producto_ID` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` VARCHAR(100) NOT NULL,
  `Tipo_producto` VARCHAR(20) NULL,
  PRIMARY KEY (`Producto_ID`),
  INDEX `tip_idx` (`Tipo_producto` ASC) VISIBLE,
  CONSTRAINT `pro`
    FOREIGN KEY (`Producto_ID`)
    REFERENCES `ventas`.`Pedido` (`Pedido_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tip`
    FOREIGN KEY (`Tipo_producto`)
    REFERENCES `ventas`.`tipos` (`playeras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`factura` ;

CREATE TABLE IF NOT EXISTS `ventas`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `cod_factura` VARCHAR(45) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fac_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fac`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ventas`.`Pedido` (`Cliente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
